# Generated by Django 3.2.6 on 2021-08-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_category_comment_post_posttag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='rareuser',
            name='created_on',
            field=models.DateField(default='2021-08-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rareuser',
            name='profile_image_url',
            field=models.CharField(default='profile_image_url', max_length=50),
            preserve_default=False,
        ),
    ]
